version: "3.9"

name: postgres-ai
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-ai:v1
    container_name: postgres-ai
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./activate-extension.sql:/docker-entrypoint-initdb.d/0-activate_extension.sql
    restart: unless-stopped
